{% set name = "Flask-DebugToolbar" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3c4e79d354ede014e6657c545a536d4fb273cc89e3fd6b4835b02e346dd3aab4

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - flask >=0.8
    - blinker

test:
  imports:
    - flask_debugtoolbar
    - flask_debugtoolbar.panels
    - flask_debugtoolbar.compat
    - flask_debugtoolbar.toolbar
    - flask_debugtoolbar.utils
  commands:
    - pip check
  requires: 
    - pip

about:
  home: http://flask-debugtoolbar.rtfd.org/
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: 'A toolbar overlay for debugging Flask applications.'
  dev_url: https://github.com/mgood/flask-debugtoolbar
  doc_url: http://flask-debugtoolbar.rtfd.org/

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
