# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6
    - CONFIG=osx_python3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "nqyuaOyGsZy2mr3GVFRmtVBEjBQAn2CM2ep19mRhZpQtlIm0EHaVU2/DdAzLNrQxxju7kk4JRpkHEGKgGB/zom17hILu1Ii3laIoBpDkskNVTdGju0TrgaBNyqazA3GSqB3lNUAJD/NGyP7qzXr34sUvgNKp26SnCVjBvNHeP101Vv4MuQW6XfKGHeqIp4z0LL08T1xN0QZ7lIk5MxpVkMd7TWHegbTh5CBUMkSpSm4LuKAkPmOcm+Rsw79FYqD77Pi8oZiKUIDhrt1L9+NcqqpwWqdWaFh20PLO/EpBotOPVUfeGKzfLG2XK4ZMeqUFp12r0Rb9KlmXdDOhf3rwudetPC4xPEOHDE6a+Xe8GGpxf9hnLL7atDDVP0Dj9Qsc8a2QRuCOfkPkRCa95H+0O19qXaSms6XJ+mR2KffyvyEx2u/3DphOVt5FhoPs1jAdKsLcV0dzg9Jrl35f/jU7WbZ8/k9/EN6tLF3YJiA2j6JlXNe+j7A4jaBbc6qXK2nJcwp1/lgAG3Z2sVyP6PtnzwnTU3gxZJrrYbWBFm3njjxA8QXoXVhAm57i6rw1KO2z+Uwgv7gtdfI7i5/VZfcF4ZHpU7trywz0osVRIr8Wxl/BtkLL8wcOKn0T+qpz0ms5Mp2amwLMpRCO1Svm/ycCXhKt8cpQkw7o/hT4nYA4sqU="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
