travis:
  secure:
    BINSTAR_TOKEN: l5si+xpznzgLBG7p6730+zajIHfDR/MzMpv0ZzGm4Hbz9hrA/CkmnA2W4fu6oOkfxWzroVYqA0nA1luTlEAHsl7OAbmVqGBLa/Lqo+XWegn/4sQNWWOegt1GTEZ1x0MF5Gh4TvnvWAbYP6w4FzEFcxT7veQLzqVB99eDTmHoFC8s8UaCKy1WTOOTVCC41Gv/wdt55j9++HNWHCeLgYHn/69zUxuYPnxtuUVB3mT1O2Wb8uqrLmSdbd8JzttHXQaFv1tNpT84xjvVvGhLyQmmoT5fGzSWWVTfxN8p3UiAH7/nPEVIF7oBHu7Eto3ejX8cA/s6n+tjhqJIdsMFhqvUSWx187RbRi7pUS7PAcUsV20aDwH7lcKkVgUSAzTviPZNMl4juXxQbwNWJ2VA81BvsN+y2/axyw+pm7CY2tJ9J1NVruePH4ilE23B2wfpgOy96vOGCxaAGwuawU6oo7HUnfyWle5gjl/8uPwTKd5wIXrEaD41S+4UQ4iexiHxZCwvqDYyM7c3KbORuvX2FERCPnMVvJ4DyBaEiWKFQuoW+p5awtIe0JCRG7uXQeYr1HmvPZR4k2CBnOnk1w/hoYSX2L9MwpBI37tfHCEPcung7A22v07igeMuA7bmAwNOFlsKqCgMepLF/hc1ofzaTbMWvDLGF1ABvgT0AfVATexxkD4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
